export const REQUEST_VEHICLES='REQUEST_VEHICLES'
export const GET_VEHICLES_FAILURE='GET_VEHICLES_FAILURE'
export const GET_VEHICLES_SUCCESS='GET_VEHICLES_SUCCESS'
export const SELECTED_VEHICLE='SELECTED_VEHICLE'
