// <auto-generated />
using MarketMotors.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketMotors.Migrations
{
    [DbContext(typeof(MarketMotorsContext))]
    partial class MarketMotorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MarketMotors.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Availability");

                    b.Property<string>("Condition");

                    b.Property<string>("Doors");

                    b.Property<string>("Engine");

                    b.Property<string>("ExteriorColor");

                    b.Property<string>("FuelType");

                    b.Property<string>("InteriorColor");

                    b.Property<string>("Make");

                    b.Property<string>("Mileage");

                    b.Property<string>("Model");

                    b.Property<string>("Price");

                    b.Property<string>("StockNumber")
                        .IsRequired();

                    b.Property<string>("Transmission");

                    b.Property<string>("VehicleTitle")
                        .IsRequired();

                    b.Property<string>("Vin")
                        .IsRequired();

                    b.Property<int>("Year");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Availability = "Available",
                            Condition = "Good",
                            Doors = "3",
                            Engine = "V8",
                            ExteriorColor = "Taupe",
                            FuelType = "Gasoline",
                            InteriorColor = "Taupe",
                            Make = "Chevy",
                            Mileage = "100,000",
                            Model = "Model",
                            Price = "2,000",
                            StockNumber = "1655",
                            Transmission = "Automatic",
                            VehicleTitle = "1998 Chevy S10",
                            Vin = "79879851655",
                            Year = 1998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
